use super::*;

#[test]
fn positive_sample_action_weight_prefers_early_role_aligned_systemic_samples_for_60d() {
    let aligned = ProbabilityTrainingRow {
        as_of_date: NaiveDate::from_ymd_opt(2007, 6, 5).unwrap(),
        market_scope: "financial_system".to_string(),
        release_id: None,
        probability_mode: Some("formal_bundle_v1".to_string()),
        freshness_status: Some("a".to_string()),
        time_to_risk_bucket: Some("us_gfc_2008".to_string()),
        split_name: Some("train".to_string()),
        features: BTreeMap::new(),
        primary_scenario_id: Some("us_gfc_2008".to_string()),
        scenario_family: Some("systemic_credit_banking_crisis".to_string()),
        scenario_training_role: Some("mandatory".to_string()),
        days_to_primary_crisis_start: Some(57),
        primary_scenario_supports_5d: false,
        primary_scenario_supports_20d: true,
        primary_scenario_supports_60d: true,
        label_5d: 0,
        label_20d: 0,
        label_60d: 1,
        regime_5d: ProbabilityTrainingRegime::Normal,
        regime_20d: ProbabilityTrainingRegime::PreWarningBuffer,
        regime_60d: ProbabilityTrainingRegime::PositiveWindow,
        action_label_5d: 0,
        action_label_20d: 1,
        action_label_60d: 1,
        prepare_episode_label: 1,
        hedge_episode_label: 1,
        defend_episode_label: 0,
        primary_action_level: Some("hedge".to_string()),
        action_episode_id: Some("us_gfc_2008:hedge".to_string()),
        action_episode_phase: "primary".to_string(),
        protected_action_window: false,
    };
    let misaligned = ProbabilityTrainingRow {
        as_of_date: NaiveDate::from_ymd_opt(2020, 2, 20).unwrap(),
        market_scope: "financial_system".to_string(),
        release_id: None,
        probability_mode: Some("formal_bundle_v1".to_string()),
        freshness_status: Some("a".to_string()),
        time_to_risk_bucket: Some("us_covid_liquidity_2020".to_string()),
        split_name: Some("train".to_string()),
        features: BTreeMap::new(),
        primary_scenario_id: Some("us_covid_liquidity_2020".to_string()),
        scenario_family: Some("acute_market_liquidity_crash".to_string()),
        scenario_training_role: Some("mandatory".to_string()),
        days_to_primary_crisis_start: Some(4),
        primary_scenario_supports_5d: true,
        primary_scenario_supports_20d: true,
        primary_scenario_supports_60d: false,
        label_5d: 1,
        label_20d: 1,
        label_60d: 1,
        regime_5d: ProbabilityTrainingRegime::PositiveWindow,
        regime_20d: ProbabilityTrainingRegime::PositiveWindow,
        regime_60d: ProbabilityTrainingRegime::PositiveWindow,
        action_label_5d: 1,
        action_label_20d: 1,
        action_label_60d: 0,
        prepare_episode_label: 0,
        hedge_episode_label: 1,
        defend_episode_label: 1,
        primary_action_level: Some("defend".to_string()),
        action_episode_id: Some("us_covid_liquidity_2020:defend".to_string()),
        action_episode_phase: "primary".to_string(),
        protected_action_window: false,
    };

    assert!(
        positive_sample_action_weight(&aligned, 60)
            > positive_sample_action_weight(&misaligned, 60)
    );
}

#[test]
fn forward_crisis_positive_weight_boosts_extension_role_on_supported_horizon() {
    let mandatory = ProbabilityTrainingRow {
        as_of_date: NaiveDate::from_ymd_opt(2007, 6, 5).unwrap(),
        market_scope: "financial_system".to_string(),
        release_id: None,
        probability_mode: Some("formal_bundle_v1".to_string()),
        freshness_status: Some("a".to_string()),
        time_to_risk_bucket: Some("us_gfc_2008".to_string()),
        split_name: Some("train".to_string()),
        features: BTreeMap::new(),
        primary_scenario_id: Some("us_gfc_2008".to_string()),
        scenario_family: Some("systemic_credit_banking_crisis".to_string()),
        scenario_training_role: Some("mandatory".to_string()),
        days_to_primary_crisis_start: Some(48),
        primary_scenario_supports_5d: false,
        primary_scenario_supports_20d: true,
        primary_scenario_supports_60d: true,
        label_5d: 0,
        label_20d: 0,
        label_60d: 1,
        regime_5d: ProbabilityTrainingRegime::Normal,
        regime_20d: ProbabilityTrainingRegime::PreWarningBuffer,
        regime_60d: ProbabilityTrainingRegime::PositiveWindow,
        action_label_5d: 0,
        action_label_20d: 1,
        action_label_60d: 1,
        prepare_episode_label: 1,
        hedge_episode_label: 1,
        defend_episode_label: 0,
        primary_action_level: Some("hedge".to_string()),
        action_episode_id: Some("us_gfc_2008:hedge".to_string()),
        action_episode_phase: "primary".to_string(),
        protected_action_window: false,
    };
    let extension = ProbabilityTrainingRow {
        as_of_date: NaiveDate::from_ymd_opt(2011, 6, 20).unwrap(),
        market_scope: "financial_system".to_string(),
        release_id: None,
        probability_mode: Some("formal_bundle_v1".to_string()),
        freshness_status: Some("a".to_string()),
        time_to_risk_bucket: Some("us_funding_stress_2011".to_string()),
        split_name: Some("train".to_string()),
        features: BTreeMap::new(),
        primary_scenario_id: Some("us_funding_stress_2011".to_string()),
        scenario_family: Some("mixed_systemic_stress".to_string()),
        scenario_training_role: Some("extension_only".to_string()),
        days_to_primary_crisis_start: Some(39),
        primary_scenario_supports_5d: false,
        primary_scenario_supports_20d: true,
        primary_scenario_supports_60d: true,
        label_5d: 0,
        label_20d: 0,
        label_60d: 1,
        regime_5d: ProbabilityTrainingRegime::Normal,
        regime_20d: ProbabilityTrainingRegime::PreWarningBuffer,
        regime_60d: ProbabilityTrainingRegime::PositiveWindow,
        action_label_5d: 0,
        action_label_20d: 1,
        action_label_60d: 1,
        prepare_episode_label: 1,
        hedge_episode_label: 1,
        defend_episode_label: 0,
        primary_action_level: Some("hedge".to_string()),
        action_episode_id: Some("us_funding_stress_2011:hedge".to_string()),
        action_episode_phase: "primary".to_string(),
        protected_action_window: true,
    };

    assert!(
        crate::forward_crisis_positive_sample_weight(&extension, 60)
            > crate::forward_crisis_positive_sample_weight(&mandatory, 60)
    );
}
